import type { NextPage } from "next";
import Head from "next/head";
import { BaseProvider } from "@metamask/providers";
import { SetStateAction, useEffect, useState } from "react";
declare global {
  interface Window {
    ethereum: BaseProvider;
  }
}
const Home: NextPage = () => {
  const [account, setAccount] = useState(null);
  const [errorMessage, setErrorMessage] = useState(null);
  const [metaMaskFlag, setMetaMaskFlag] = useState(false);

  useEffect(() => {
    const tmpFlag = window.ethereum && window.ethereum.isMetaMask;
    setMetaMaskFlag(tmpFlag);
  }, []);

  const connectWallet = () => {
    window.ethereum
      .request({ method: "eth_requestAccounts" })
      .then((result: SetStateAction<null>[]) => {
        setAccount(result[0]);
      })
      .catch((error: { message: SetStateAction<null> }) => {
        setErrorMessage(error.message);
      });
  };

  const Disconnect = () => {
    setErrorMessage(null);
    setAccount(null);
  };

  return (
    <div>
      <Head>
        <title>Top</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto py-4">
        <h1 className="text-4xl">
          Welcome to <span className="text-blue-500">Example!</span>
        </h1>
        <div className="bg-white p-4 m-4 rounded-xl">
          <div className="space-y-2">
            <div>
              {account ? (
                <div className="flex space-x-2">
                  <button className="bg-black rounded-xl px-4 py-2">
                    <span className="text-white" onClick={Disconnect}>
                      Disconnect!
                    </span>
                  </button>
                </div>
              ) : (
                <button
                  onClick={connectWallet}
                  className="bg-black rounded-xl px-4 py-2"
                >
                  <span className="text-white">Please Wallet Connect!</span>
                </button>
              )}
            </div>
            {account ? <div className="text-black">{account}</div> : null}
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
